### ISSUE TITLE
Website auth timing out

### ISSUE THREAD

**Issue by jamesctucker** [robinetbatman/figma-lottie#16]
Is this project dead?

Wondering because I'm trying to authenticate via my Figma account but the connection keeps timing out.

Specifically this route --> https://api.tacos.wtf/chicken/v1/o.

**Comment by BaptisteAmato** [comment]
Hi @jamesctucker, the server is not maintained anymore indeed, but you can easily run it locally or on your own server :) Don't hesitate if you need help with that!

Baptiste

**Comment by jamesctucker** [comment]
Thanks for the reply, @BaptisteAmato! I will try local deployment.
